apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-configmap
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "list", "watch", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-configmap
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflow-configmap
subjects:
  - kind: ServiceAccount
    name: argo-workflow
    namespace: default
